services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    profiles:
      - "core"
      - "data"
      - "trading"

  market_poller:
    build:
      context: .
      dockerfile: services/market_poller/Dockerfile
    env_file:
      - .env
      - .env.data
    depends_on:
      - redis
    profiles:
      - "data"

  market_similarity:
    build:
      context: .
      dockerfile: services/market_similarity/Dockerfile
    env_file:
      - .env
      - .env.data
    depends_on:
      - redis
    profiles:
      - "data"

  arbitrage_finder:
    build:
      context: .
      dockerfile: services/arbitrage_finder/Dockerfile
    env_file:
      - .env
      - .env.trading
    depends_on:
      - redis
    profiles:
      - "trading"
  
  trade_executor:
    build:
      context: .
      dockerfile: services/trade_executor/Dockerfile
    env_file:
      - .env
      - .env.trading
    depends_on:
      - redis
    profiles:
      - "trading"

volumes:
  redis-data: 