services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    profiles:
      - "core"
      - "data"
      - "trading"

  market-poller:
    build:
      context: .
      dockerfile: services/market-poller/Dockerfile
    env_file:
      - .env
      - .env.data
    depends_on:
      - redis
    profiles:
      - "data"

  market-similarity:
    build:
      context: .
      dockerfile: services/market-similarity/Dockerfile
    env_file:
      - .env
      - .env.data
    depends_on:
      - redis
    profiles:
      - "data"

  arbitrage-finder:
    build:
      context: .
      dockerfile: services/arbitrage-finder/Dockerfile
    env_file:
      - .env
      - .env.trading
    depends_on:
      - redis
    profiles:
      - "trading"
  
  trade-executor:
    build:
      context: .
      dockerfile: services/trade-executor/Dockerfile
    env_file:
      - .env
      - .env.trading
    depends_on:
      - redis
    profiles:
      - "trading"

volumes:
  redis-data: 